export const CMD = {
  GUILD_CREATE: 'GUILD_CREATE',
  GUILD_JOIN: 'GUILD_JOIN',
  GUILD_LEAVE: 'GUILD_LEAVE',
  GUILD_DELETE: 'GUILD_DELETE',
  GUILD_CHANGE_ROLE: 'GUILD_CHANGE_ROLE',
  GUILD_ACCEPT_MEMBER: 'GUILD_ACCEPT_MEMBER',
  GUILD_AUTO_ACCEPT: 'GUILD_AUTO_ACCEPT',
  GUILD_FIND_GUILD: 'GUILD_FIND_GUILD',
  GUILD_DONATE: 'GUILD_DONATE',
  GUILD_BLOCK_LIST: 'GUILD_BLOCK_LIST',
};
